services:
  java-theory-trainer-db:
    image: postgres:16-alpine
    container_name: java-theory-trainer-db
    restart: unless-stopped

    ports:
      - "${DB_PORT}:5432"

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - java_theory_trainer_db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  java_theory_trainer_db_data: